#!/bin/bash

cmake -DCMAKE_BUILD_TYPE=Release \
	-DBUILD_SHARED_LIBS:BOOL=ON \
	-DCMAKE_INSTALL_PREFIX=/home/fabidi89/Paraview-v5.2.0 \
	-DPARAVIEW_ENABLE_PYTHON:BOOL=ON \
	-DPARAVIEW_USE_MPI:BOOL=ON \
	-DBUILD_TESTING:BOOL=OFF \
	-DPARAVIEW_BUILD_PLUGIN_SurfaceLIC:BOOL=OFF \
	../../ParaView
